version: '3.9'

services:
  # PostgreSQL 16 s pgvector extension
  postgres:
    image: pgvector/pgvector:pg16
    container_name: jobsphere-postgres
    restart: unless-stopped
    environment:
      POSTGRES_USER: jobsphere
      POSTGRES_PASSWORD: jobsphere_dev_pass
      POSTGRES_DB: jobsphere
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./apps/web/prisma/migrations:/docker-entrypoint-initdb.d
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U jobsphere"]
      interval: 10s
      timeout: 5s
      retries: 5

  # Redis pre cache, queue, rate limiting
  redis:
    image: redis:7-alpine
    container_name: jobsphere-redis
    restart: unless-stopped
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 3s
      retries: 5
    command: redis-server --appendonly yes --maxmemory 512mb --maxmemory-policy allkeys-lru

  # MinIO (S3-kompatibilné storage)
  minio:
    image: minio/minio:latest
    container_name: jobsphere-minio
    restart: unless-stopped
    environment:
      MINIO_ROOT_USER: minioadmin
      MINIO_ROOT_PASSWORD: minioadmin123
    ports:
      - "9000:9000"
      - "9001:9001"
    volumes:
      - minio_data:/data
    command: server /data --console-address ":9001"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:9000/minio/health/live"]
      interval: 30s
      timeout: 20s
      retries: 3

  # MinIO Client - vytvorí bucket pri štarte
  minio-init:
    image: minio/mc:latest
    container_name: jobsphere-minio-init
    depends_on:
      - minio
    entrypoint: >
      /bin/sh -c "
      sleep 5;
      /usr/bin/mc alias set myminio http://minio:9000 minioadmin minioadmin123;
      /usr/bin/mc mb myminio/jobsphere-cvs --ignore-existing;
      /usr/bin/mc mb myminio/jobsphere-documents --ignore-existing;
      /usr/bin/mc anonymous set download myminio/jobsphere-cvs;
      /usr/bin/mc anonymous set download myminio/jobsphere-documents;
      exit 0;
      "

  # Meilisearch (BM25 full-text search)
  meilisearch:
    image: getmeili/meilisearch:v1.5
    container_name: jobsphere-meilisearch
    restart: unless-stopped
    environment:
      MEILI_MASTER_KEY: jobsphere_meili_master_key_dev
      MEILI_ENV: development
      MEILI_NO_ANALYTICS: "true"
    ports:
      - "7700:7700"
    volumes:
      - meilisearch_data:/meili_data
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:7700/health"]
      interval: 10s
      timeout: 5s
      retries: 5

  # ClamAV (Antivirus scanning)
  clamav:
    image: clamav/clamav:latest
    container_name: jobsphere-clamav
    restart: unless-stopped
    ports:
      - "3310:3310"
    volumes:
      - clamav_data:/var/lib/clamav
    healthcheck:
      test: ["CMD", "/usr/local/bin/clamdcheck.sh"]
      interval: 60s
      timeout: 30s
      retries: 3
      start_period: 120s

  # MailHog (Email testing)
  mailhog:
    image: mailhog/mailhog:latest
    container_name: jobsphere-mailhog
    restart: unless-stopped
    ports:
      - "1025:1025"  # SMTP
      - "8025:8025"  # Web UI
    healthcheck:
      test: ["CMD", "wget", "--quiet", "--tries=1", "--spider", "http://localhost:8025"]
      interval: 10s
      timeout: 5s
      retries: 3

  # pgBouncer (Connection pooling)
  pgbouncer:
    image: pgbouncer/pgbouncer:latest
    container_name: jobsphere-pgbouncer
    restart: unless-stopped
    environment:
      DATABASES_HOST: postgres
      DATABASES_PORT: 5432
      DATABASES_USER: jobsphere
      DATABASES_PASSWORD: jobsphere_dev_pass
      DATABASES_DBNAME: jobsphere
      PGBOUNCER_POOL_MODE: transaction
      PGBOUNCER_MAX_CLIENT_CONN: 1000
      PGBOUNCER_DEFAULT_POOL_SIZE: 25
    ports:
      - "6432:6432"
    depends_on:
      postgres:
        condition: service_healthy

volumes:
  postgres_data:
    driver: local
  redis_data:
    driver: local
  minio_data:
    driver: local
  meilisearch_data:
    driver: local
  clamav_data:
    driver: local

networks:
  default:
    name: jobsphere-network
