# Railway Configuration for JobSphere Backend
# Deploy API + Workers together

[build]
builder = "NIXPACKS"
buildCommand = "pnpm install && pnpm build"

[deploy]
numReplicas = 1
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 10

# API Service
[[services]]
name = "api"
startCommand = "pnpm --filter @jobsphere/api start"

[services.healthcheck]
path = "/health"
port = 4000
interval = 30
timeout = 10

[[services.ports]]
port = 4000
protocol = "http"

# Workers Service (runs alongside API)
[[services]]
name = "workers"
startCommand = "pnpm --filter @jobsphere/workers start"

[services.healthcheck]
# Workers don't have HTTP endpoint, use Redis connection check
command = "redis-cli -u $REDIS_URL ping"
interval = 30
timeout = 10

# Environment Variables (set in Railway dashboard)
# DATABASE_URL
# REDIS_URL
# ANTHROPIC_API_KEY
# JWT_SECRET
# COOKIE_SECRET
# STRIPE_SECRET_KEY
# STRIPE_WEBHOOK_SECRET
# S3_BUCKET
# S3_ACCESS_KEY
# S3_SECRET_KEY
# NEXT_PUBLIC_APP_URL (Vercel URL)
